# Generated by Django 5.0.7 on 2024-07-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DOB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('age_years', models.IntegerField(blank=True, null=True)),
                ('age_months', models.IntegerField(blank=True, null=True)),
                ('age_days', models.IntegerField(blank=True, null=True)),
                ('test_case_type', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
