# Generated by Django 5.0.7 on 2024-07-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dob',
            name='test_case_type',
            field=models.CharField(default='Nominal', max_length=20),
            preserve_default=False,
        ),
    ]
