# Generated by Django 5.0.6 on 2024-08-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_dob_test_case_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dob',
            name='is_future_date',
            field=models.BooleanField(default=False),
        ),
    ]
