# Generated by Django 5.0.6 on 2024-08-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_remove_dob_is_future_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dob',
            name='is_future_date',
            field=models.BooleanField(default=False),
        ),
    ]
